ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install dependencies
RUN pip install \
    albumentations \
    h5py \
    warmup_scheduler \
    diffusers==0.11.1 \
    vit-pytorch \
    efficientnet_pytorch \
    "git+https://github.com/robodhruv/visualnav-transformer.git@main#egg=vint-train&subdirectory=train"

RUN pip install -e git+https://github.com/real-stanford/diffusion_policy.git@main#egg=diffusion_policy