ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install apt dependencies and add repositories
RUN apt-get update && \
    apt-get install -y software-properties-common apt-utils wget && \
    add-apt-repository universe -y && \
    add-apt-repository ppa:borglab/gtsam-release-4.2 -y && \
    apt-get update && \
    apt-get install -y \
        tmux tmuxinator iputils-ping i2c-tools \
        ros-humble-ros-gz-sim \
        ros-humble-ros-gz-bridge \
        python3-jinja2 \
        python3-pydantic \
        ros-humble-ament-cmake-clang-format \
        ros-humble-geographic-msgs \
        libgeographic-dev \
        python3-tk \
        python3-rosdep \
        python3-pip \
        python3-colcon-common-extensions \
        python3-colcon-mixin \
        ros-dev-tools \
        python3-flake8 \
        python3-flake8-polyfill \
        python3-flake8-docstrings \
        cppcheck lcov \
        libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
        python3-wstool \
        ros-humble-mocap4r2-msgs \
        ros-humble-mocap4r2-control \
        ros-humble-teleop-twist-joy \
        libpcl-dev \
        ros-humble-pcl-conversions \
        ros-humble-pcl-ros \
        libapr1-dev libaprutil1-dev \
        libgoogle-glog-dev libeigen3-dev libyaml-cpp-dev \
        libgtsam-dev libgtsam-unstable-dev && \
    rm -rf /var/lib/apt/lists/*

# Install pip dependencies
RUN python3 -m pip install --upgrade pip && \
    pip3 install \
        kconfiglib smbus jinja2 empy jsonschema pyros-genmsg packaging toml numpy future \
        freesimplegui pymap3d \
        pylint flake8==4.0.1 pycodestyle==2.8 cmakelint cpplint \
        colcon-lcov-result \
        ultralytics seaborn opencv-python numpy==1.* albumentations h5py warmup_scheduler \
        diffusers==0.11.1 vit-pytorch efficientnet_pytorch \
        "git+https://github.com/robodhruv/visualnav-transformer.git@main#egg=vint-train&subdirectory=train" && \
    pip3 install -e git+https://github.com/real-stanford/diffusion_policy.git@main#egg=diffusion_policy

# Colcon mixin setup
RUN colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update default && \
    rm -rf log

# Gazebo key and repo
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | \
    tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    apt-get update

RUN apt-get install -y ros-${ROS_DISTRO}-octomap-ros && rm -f /etc/apt/sources.list.d/isaac-ros.list && \
    apt-get install -y ros-humble-camera-calibration && \
    apt-get install -y ros-${ROS_DISTRO}-marti-common-msgs

RUN apt-get install -y libgl1 libglib2.0-0 libsm6 libxext6 libxrender1 libx11-xcb1 libxkbcommon-x11-0 libxcb1 libxcb-xinerama0 libavcodec-extra ros-humble-ffmpeg-image-transport ros-humble-depthai ros-humble-foxglove-msgs ros-humble-rviz-imu-plugin gedit

# Copy scripts and set permissions !!! must be last to leverage docker cache !!!
COPY scripts/*entrypoint.sh /usr/local/bin/scripts/
RUN chmod +x /usr/local/bin/scripts/*.sh || true

COPY scripts/entrypoint_addition[s]/*.sh /usr/local/bin/scripts/entrypoint_additions/
RUN chmod +x /usr/local/bin/scripts/entrypoint_additions/*.sh || true